/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence_system;

/**
 *
 * @author Dilshani
 */
public class Helicopter extends javax.swing.JFrame implements Observer{
        /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        setTitle("Helicopter");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAreaClear = new javax.swing.JLabel();
        btnHeliShoot = new javax.swing.JButton();
        btnHeliMissile = new javax.swing.JButton();
        btnHeliLaser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHelicopter = new javax.swing.JTextArea();
        txtFildHelicopter = new javax.swing.JTextField();
        btnHeliSend = new javax.swing.JButton();
        sliderHeliEnergy = new javax.swing.JSlider();
        spinrHeliSoldier = new javax.swing.JSpinner();
        spinrHeliAmmo = new javax.swing.JSpinner();
        heliPositionCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnHeliAmmo = new javax.swing.JLabel();
        lblHeliSoldier = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(5, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAreaClear.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblAreaClear.setForeground(new java.awt.Color(102, 0, 0));
        lblAreaClear.setText("Area Not Cleared");
        getContentPane().add(lblAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnHeliShoot.setBackground(new java.awt.Color(51, 51, 51));
        btnHeliShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHeliShoot.setForeground(new java.awt.Color(255, 153, 153));
        btnHeliShoot.setText("Shoot");
        btnHeliShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeliShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnHeliShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 118, -1));

        btnHeliMissile.setBackground(new java.awt.Color(51, 51, 51));
        btnHeliMissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHeliMissile.setForeground(new java.awt.Color(255, 51, 51));
        btnHeliMissile.setText("Missile Operation");
        btnHeliMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeliMissileActionPerformed(evt);
            }
        });
        getContentPane().add(btnHeliMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 114, -1));

        btnHeliLaser.setBackground(new java.awt.Color(51, 51, 51));
        btnHeliLaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHeliLaser.setForeground(new java.awt.Color(255, 0, 0));
        btnHeliLaser.setText("Laser Operation");
        getContentPane().add(btnHeliLaser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 114, -1));

        txtAreaHelicopter.setColumns(20);
        txtAreaHelicopter.setRows(5);
        jScrollPane1.setViewportView(txtAreaHelicopter);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 128, 388, 122));
        getContentPane().add(txtFildHelicopter, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 262, 287, -1));

        btnHeliSend.setBackground(new java.awt.Color(0, 0, 0));
        btnHeliSend.setForeground(new java.awt.Color(255, 255, 255));
        btnHeliSend.setText("Send");
        btnHeliSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHeliSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeliSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnHeliSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 262, -1, -1));

        sliderHeliEnergy.setBackground(new java.awt.Color(51, 0, 153));
        sliderHeliEnergy.setForeground(new java.awt.Color(255, 51, 0));
        sliderHeliEnergy.setMajorTickSpacing(20);
        sliderHeliEnergy.setMinorTickSpacing(10);
        sliderHeliEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderHeliEnergy.setPaintLabels(true);
        sliderHeliEnergy.setPaintTicks(true);
        sliderHeliEnergy.setSnapToTicks(true);
        sliderHeliEnergy.setValue(85);
        getContentPane().add(sliderHeliEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 262));

        spinrHeliSoldier.setValue(6);
        getContentPane().add(spinrHeliSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 41, -1));

        spinrHeliAmmo.setValue(450);
        getContentPane().add(spinrHeliAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 41, -1));

        heliPositionCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        heliPositionCheckBox.setText("Position");
        heliPositionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliPositionCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(heliPositionCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        btnHeliAmmo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHeliAmmo.setText("Ammo Count");
        getContentPane().add(btnHeliAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        lblHeliSoldier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeliSoldier.setText("Soldier Count");
        getContentPane().add(lblHeliSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dilshani\\Desktop\\Helicopter Cover 1.1.png")); // NOI18N
        jLabel3.setText("Energy");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHeliMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeliMissileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHeliMissileActionPerformed

    private void btnHeliSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeliSendActionPerformed
        // TODO add your handling code here:
        //MainController mainController = new MainController();
        String ab = txtFildHelicopter.getText();
        MainController.txtAreaMainIncomeMsg.append("Helicopter :"+ab+"\n");
        txtFildHelicopter.setText("");
        //System.out.println(jTextField1.getText());
    }//GEN-LAST:event_btnHeliSendActionPerformed

    private void heliPositionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliPositionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliPositionCheckBoxActionPerformed

    private void btnHeliShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeliShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHeliShootActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHeliAmmo;
    private javax.swing.JButton btnHeliLaser;
    private javax.swing.JButton btnHeliMissile;
    private javax.swing.JButton btnHeliSend;
    private javax.swing.JButton btnHeliShoot;
    private javax.swing.JCheckBox heliPositionCheckBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAreaClear;
    private javax.swing.JLabel lblHeliSoldier;
    public static javax.swing.JSlider sliderHeliEnergy;
    public static javax.swing.JSpinner spinrHeliAmmo;
    public static javax.swing.JSpinner spinrHeliSoldier;
    private javax.swing.JTextArea txtAreaHelicopter;
    private javax.swing.JTextField txtFildHelicopter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear(boolean clear) {
     if(clear==true){
         lblAreaClear.setText("Area Cleared");
     }else{
         lblAreaClear.setText("Area Not Cleared");
     }
    }

    @Override
    public void message(String msg, boolean checkSend, int index) {
        if(checkSend==true && index==1){
            txtAreaHelicopter.append(msg+"\n");
           //System.out.println(msg);
        } else if(checkSend == false) {
            txtAreaHelicopter.append(msg+"\n");
        }
        
    }

    @Override
    public void strenth(int stren) {
        if(heliPositionCheckBox.isSelected()){
            if(stren>0){
                btnHeliShoot.setEnabled(true);
            } else {
                btnHeliShoot.setEnabled(false);
            }
            if(stren>20){
                btnHeliMissile.setEnabled(true);
            } else {
                btnHeliMissile.setEnabled(false);
            }
            if(stren>60){
                btnHeliLaser.setEnabled(true);
            }else{
                btnHeliLaser.setEnabled(false);
            }   
        } else {
            btnHeliShoot.setEnabled(false);
            btnHeliMissile.setEnabled(false);
            btnHeliLaser.setEnabled(false);
            
        }
    
    }
}
