/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Dilshani
 */
public class MainController extends javax.swing.JFrame {
    private Observable observable;

    /**
     * Creates new form MainController
     */
    public MainController(Observable observable) {
        this.observable = observable;
        setTitle("Main Controller");
        initComponents();
    }
    
    public MainController(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCollectInfo = new javax.swing.JButton();
        chckBxAreaClear = new javax.swing.JCheckBox();
        txtAreaMainSentMsg = new java.awt.TextArea();
        chckBoxSendPrivate = new javax.swing.JCheckBox();
        btnMainSend = new javax.swing.JButton();
        txtAreaMainIncomeMsg = new java.awt.TextArea();
        slderMain = new javax.swing.JSlider();
        lblMainSoldier = new javax.swing.JLabel();
        lblMainFuel = new javax.swing.JLabel();
        lblMainAmmo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbBxSelectDefence = new javax.swing.JComboBox<>();
        lblSoldierCount = new javax.swing.JLabel();
        lblFuelCount = new javax.swing.JLabel();
        lblAmmoCount = new javax.swing.JLabel();
        lblMainOxigen = new javax.swing.JLabel();
        lblOxigenCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(5, 5));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCollectInfo.setBackground(new java.awt.Color(0, 51, 204));
        btnCollectInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnCollectInfo.setText("Collect Informations");
        btnCollectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCollectInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        chckBxAreaClear.setBackground(new java.awt.Color(0, 0, 0));
        chckBxAreaClear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        chckBxAreaClear.setForeground(new java.awt.Color(153, 153, 255));
        chckBxAreaClear.setText("Area Clear");
        chckBxAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckBxAreaClearActionPerformed(evt);
            }
        });
        getContentPane().add(chckBxAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));
        getContentPane().add(txtAreaMainSentMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 250, 130));

        chckBoxSendPrivate.setBackground(new java.awt.Color(0, 0, 0));
        chckBoxSendPrivate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chckBoxSendPrivate.setForeground(new java.awt.Color(255, 255, 255));
        chckBoxSendPrivate.setText("Send Private");
        chckBoxSendPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckBoxSendPrivateActionPerformed(evt);
            }
        });
        getContentPane().add(chckBoxSendPrivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        btnMainSend.setBackground(new java.awt.Color(153, 153, 255));
        btnMainSend.setForeground(new java.awt.Color(255, 255, 255));
        btnMainSend.setText("Send");
        btnMainSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMainSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));
        getContentPane().add(txtAreaMainIncomeMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 110));

        slderMain.setBackground(new java.awt.Color(255, 0, 0));
        slderMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slderMain.setForeground(new java.awt.Color(255, 255, 255));
        slderMain.setMajorTickSpacing(20);
        slderMain.setMinorTickSpacing(10);
        slderMain.setPaintLabels(true);
        slderMain.setPaintTicks(true);
        slderMain.setSnapToTicks(true);
        slderMain.setValue(0);
        slderMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slderMainStateChanged(evt);
            }
        });
        getContentPane().add(slderMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 290, -1));

        lblMainSoldier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainSoldier.setForeground(new java.awt.Color(255, 255, 255));
        lblMainSoldier.setText("Soldier Count");
        getContentPane().add(lblMainSoldier, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblMainFuel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainFuel.setForeground(new java.awt.Color(255, 255, 255));
        lblMainFuel.setText("Fuel Amount");
        getContentPane().add(lblMainFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        lblMainAmmo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainAmmo.setForeground(new java.awt.Color(255, 255, 255));
        lblMainAmmo.setText("Ammo Amount");
        getContentPane().add(lblMainAmmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Position");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cmbBxSelectDefence.setBackground(new java.awt.Color(204, 255, 204));
        cmbBxSelectDefence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarine" }));
        getContentPane().add(cmbBxSelectDefence, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 117, -1));

        lblSoldierCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblSoldierCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 30, 10));

        lblFuelCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFuelCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 20, -1));

        lblAmmoCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 30, -1));

        lblMainOxigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMainOxigen.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblMainOxigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 84, 19));

        lblOxigenCount.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblOxigenCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 30, 12));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 102));
        jLabel6.setText("Sent Messages");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("Incoming Messages");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dilshani\\Desktop\\Main Cover1.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckBxAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckBxAreaClearActionPerformed
        // TODO add your handling code here:
        //checkBoxAreaClear.addActionListener(new ActionListener(){
            //@Override
            //public void actionPerformed(ActionEvent e) {
                boolean ab = chckBxAreaClear.isSelected();
                System.out.println(ab);
                if(ab==true){
                    observable.setClear(true);
                }else{
                    observable.setClear(false);
                }
            //}
            
        //});
    }//GEN-LAST:event_chckBxAreaClearActionPerformed

    private void slderMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slderMainStateChanged
        // TODO add your handling code here:
        slderMain.addChangeListener(new ChangeListener(){
            @Override
           public void stateChanged (ChangeEvent e){
                observable.setStrenth(slderMain.getValue());
            }
        });
    }//GEN-LAST:event_slderMainStateChanged

    private void btnMainSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainSendActionPerformed
        // TODO add your handling code here:
        //btnSend.addActionListener(new ActionListener(){
    //public void actionPerformed(ActionEvent e) {
             String msg = txtAreaMainSentMsg.getText();
             boolean checkSend = chckBoxSendPrivate.isSelected();
             int index = cmbBxSelectDefence.getSelectedIndex();
             observable.setMsg(msg,checkSend,index);
             txtAreaMainSentMsg.setText("");//Clear Box
             
            //}
        //});
    }//GEN-LAST:event_btnMainSendActionPerformed

    private void btnCollectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectInfoActionPerformed
        // TODO add your handling code here:
        int indexNum = cmbBxSelectDefence.getSelectedIndex();
        if(indexNum == 1){
            lblSoldierCount.setText(""+Helicopter.spinrHeliSoldier.getValue());
            lblFuelCount.setText(""+Helicopter.sliderHeliEnergy.getValue());
            lblAmmoCount.setText(""+Helicopter.spinrHeliAmmo.getValue());
            lblMainOxigen.setText("");
            lblOxigenCount.setText("");
        } else if(indexNum == 2){
            lblSoldierCount.setText(""+Tank.spinrTankSoldierCount.getValue());
            lblFuelCount.setText(""+Tank.slidrTankEnergy.getValue());
            lblAmmoCount.setText(""+Tank.spinrTankAmmoCount.getValue());
            lblMainOxigen.setText("");
            lblOxigenCount.setText("");
        } else {
            lblSoldierCount.setText(""+Submarine.spinrSubSoldieCount.getValue());
            lblFuelCount.setText(""+Submarine.sldrSubEnergy.getValue());
            lblAmmoCount.setText(""+Submarine.spinerSubAmmoCount.getValue());
            lblMainOxigen.setText("Oxigen Ammount");
            lblOxigenCount.setText(""+Submarine.sldrSubOxigen.getValue());
            
        }
    }//GEN-LAST:event_btnCollectInfoActionPerformed

    private void chckBoxSendPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckBoxSendPrivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckBoxSendPrivateActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollectInfo;
    private javax.swing.JButton btnMainSend;
    private javax.swing.JCheckBox chckBoxSendPrivate;
    private javax.swing.JCheckBox chckBxAreaClear;
    private javax.swing.JComboBox<String> cmbBxSelectDefence;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblFuelCount;
    private javax.swing.JLabel lblMainAmmo;
    private javax.swing.JLabel lblMainFuel;
    private javax.swing.JLabel lblMainOxigen;
    private javax.swing.JLabel lblMainSoldier;
    private javax.swing.JLabel lblOxigenCount;
    public static javax.swing.JLabel lblSoldierCount;
    private javax.swing.JSlider slderMain;
    public static java.awt.TextArea txtAreaMainIncomeMsg;
    private java.awt.TextArea txtAreaMainSentMsg;
    // End of variables declaration//GEN-END:variables
}
