/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence_system;

/**
 *
 * @author Dilshani
 */
public class Tank extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Tank
     */
    public Tank() {
        setTitle("Tank");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTankAreaClear = new javax.swing.JLabel();
        btnTankShoot = new javax.swing.JButton();
        btnTankMissile = new javax.swing.JButton();
        btnTankRedar = new javax.swing.JButton();
        btnTankRotate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        tankSendBtn = new javax.swing.JButton();
        chckBxTankPosition = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinrTankSoldierCount = new javax.swing.JSpinner();
        spinrTankAmmoCount = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        slidrTankEnergy = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTankAreaClear.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTankAreaClear.setForeground(new java.awt.Color(102, 0, 0));
        lblTankAreaClear.setText("Area Not Cleared");
        getContentPane().add(lblTankAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 18, -1, -1));

        btnTankShoot.setBackground(new java.awt.Color(51, 51, 51));
        btnTankShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTankShoot.setForeground(new java.awt.Color(255, 204, 204));
        btnTankShoot.setText("Shoot");
        getContentPane().add(btnTankShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 72, 116, -1));

        btnTankMissile.setBackground(new java.awt.Color(51, 51, 51));
        btnTankMissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTankMissile.setForeground(new java.awt.Color(255, 153, 153));
        btnTankMissile.setText("Missile Operation");
        getContentPane().add(btnTankMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 72, 111, -1));

        btnTankRedar.setBackground(new java.awt.Color(51, 51, 51));
        btnTankRedar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTankRedar.setForeground(new java.awt.Color(255, 51, 51));
        btnTankRedar.setText("Redar Operation");
        getContentPane().add(btnTankRedar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 102, -1, -1));

        btnTankRotate.setBackground(new java.awt.Color(51, 51, 51));
        btnTankRotate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTankRotate.setForeground(new java.awt.Color(204, 0, 0));
        btnTankRotate.setText("Rotate Shooting");
        getContentPane().add(btnTankRotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 102, 111, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 155, 399, 118));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 285, 331, -1));

        tankSendBtn.setBackground(new java.awt.Color(0, 0, 0));
        tankSendBtn.setForeground(new java.awt.Color(255, 255, 255));
        tankSendBtn.setText("Send");
        tankSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankSendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(tankSendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 285, -1, -1));

        chckBxTankPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chckBxTankPosition.setText("Position");
        getContentPane().add(chckBxTankPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ammo Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        spinrTankSoldierCount.setValue(25);
        getContentPane().add(spinrTankSoldierCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 42, -1));

        spinrTankAmmoCount.setValue(750);
        getContentPane().add(spinrTankAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 42, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Energy");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        slidrTankEnergy.setBackground(new java.awt.Color(51, 0, 153));
        slidrTankEnergy.setForeground(new java.awt.Color(255, 51, 0));
        slidrTankEnergy.setMajorTickSpacing(20);
        slidrTankEnergy.setMinorTickSpacing(10);
        slidrTankEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        slidrTankEnergy.setPaintLabels(true);
        slidrTankEnergy.setPaintTicks(true);
        slidrTankEnergy.setSnapToTicks(true);
        slidrTankEnergy.setValue(75);
        getContentPane().add(slidrTankEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 286));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dilshani\\Desktop\\Tank Cover1.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tankSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankSendBtnActionPerformed
        // TODO add your handling code here:
        //MainController mainController = new MainController();
        String ab = jTextField1.getText();
        MainController.txtAreaMainIncomeMsg.append("Tank : "+ab+"\n");
        jTextField1.setText("");
    }//GEN-LAST:event_tankSendBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTankMissile;
    private javax.swing.JButton btnTankRedar;
    private javax.swing.JButton btnTankRotate;
    private javax.swing.JButton btnTankShoot;
    private javax.swing.JCheckBox chckBxTankPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTankAreaClear;
    public static javax.swing.JSlider slidrTankEnergy;
    public static javax.swing.JSpinner spinrTankAmmoCount;
    public static javax.swing.JSpinner spinrTankSoldierCount;
    private javax.swing.JButton tankSendBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear(boolean clear) {
     if(clear==true){
         lblTankAreaClear.setText("Area Cleared");
     }else{
         lblTankAreaClear.setText("Area Not Cleared");
     }
    }

    @Override
    public void message(String msg, boolean checkSend, int index) {
        if(checkSend==true && index==2){
            jTextArea1.append(msg+"\n");
           //System.out.println(msg);
        } else if(checkSend == false) {
            jTextArea1.append(msg+"\n");
        }
       // jTextArea1.append(msg+"\n");
    }


    @Override
    public void strenth(int stren) {
        if(chckBxTankPosition.isSelected()){
            if(stren>0){
                btnTankShoot.setEnabled(true);
            } else {
                btnTankShoot.setEnabled(false);
            }
            if(stren>20){
                btnTankMissile.setEnabled(true);
            } else {
                btnTankMissile.setEnabled(false);
            }
            if(stren>60){
                btnTankRedar.setEnabled(true);
            }else{
                btnTankRedar.setEnabled(false);
            }
            if(stren>80){
                btnTankRotate.setEnabled(true);
            } else {
                btnTankRotate.setEnabled(false);
            }
        } else {
            btnTankShoot.setEnabled(false);
            btnTankMissile.setEnabled(false);
            btnTankRedar.setEnabled(false);
            btnTankRotate.setEnabled(false);
        }
    }
}
