/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence_system;

/**
 *
 * @author Dilshani
 */
public class Submarine extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Submarine
     */
    public Submarine() {
        setTitle("Submarine");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubAreaClear = new javax.swing.JLabel();
        btnSubShoot = new javax.swing.JButton();
        btnSubTomahawk = new javax.swing.JButton();
        btnSubSonar = new javax.swing.JButton();
        btnSubTrident = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSubmarine = new javax.swing.JTextArea();
        txtFieldSubmarine = new javax.swing.JTextField();
        btnSubSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chckBxSubPosition = new javax.swing.JCheckBox();
        spinrSubSoldieCount = new javax.swing.JSpinner();
        spinerSubAmmoCount = new javax.swing.JSpinner();
        sldrSubEnergy = new javax.swing.JSlider();
        sldrSubOxigen = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 5));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubAreaClear.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblSubAreaClear.setForeground(new java.awt.Color(102, 0, 0));
        lblSubAreaClear.setText("Area Not Cleared");
        getContentPane().add(lblSubAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnSubShoot.setBackground(new java.awt.Color(102, 102, 102));
        btnSubShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubShoot.setForeground(new java.awt.Color(255, 204, 204));
        btnSubShoot.setText("Shoot");
        getContentPane().add(btnSubShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 118, -1));

        btnSubTomahawk.setBackground(new java.awt.Color(102, 102, 102));
        btnSubTomahawk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubTomahawk.setForeground(new java.awt.Color(255, 102, 102));
        btnSubTomahawk.setText("Tomahawk Missile");
        getContentPane().add(btnSubTomahawk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 118, -1));

        btnSubSonar.setBackground(new java.awt.Color(102, 102, 102));
        btnSubSonar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubSonar.setForeground(new java.awt.Color(255, 153, 153));
        btnSubSonar.setText("Sonar Operation");
        getContentPane().add(btnSubSonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 56, 118, -1));

        btnSubTrident.setBackground(new java.awt.Color(102, 102, 102));
        btnSubTrident.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubTrident.setForeground(new java.awt.Color(255, 0, 0));
        btnSubTrident.setText("Trident-2 Missile");
        getContentPane().add(btnSubTrident, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 118, -1));

        txtAreaSubmarine.setColumns(20);
        txtAreaSubmarine.setRows(5);
        jScrollPane1.setViewportView(txtAreaSubmarine);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, 362, 126));

        txtFieldSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSubmarineActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldSubmarine, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 274, 286, -1));

        btnSubSend.setBackground(new java.awt.Color(0, 0, 0));
        btnSubSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSubSend.setText("Send");
        btnSubSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel1.setText("Soldier Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setText("Ammo Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        chckBxSubPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chckBxSubPosition.setText("Position");
        getContentPane().add(chckBxSubPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        spinrSubSoldieCount.setValue(56);
        getContentPane().add(spinrSubSoldieCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, -1));

        spinerSubAmmoCount.setValue(850);
        getContentPane().add(spinerSubAmmoCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 50, -1));

        sldrSubEnergy.setBackground(new java.awt.Color(51, 0, 153));
        sldrSubEnergy.setForeground(new java.awt.Color(255, 51, 0));
        sldrSubEnergy.setMajorTickSpacing(20);
        sldrSubEnergy.setMinorTickSpacing(10);
        sldrSubEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrSubEnergy.setPaintLabels(true);
        sldrSubEnergy.setPaintTicks(true);
        sldrSubEnergy.setSnapToTicks(true);
        sldrSubEnergy.setValue(80);
        getContentPane().add(sldrSubEnergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 257));

        sldrSubOxigen.setBackground(new java.awt.Color(0, 204, 102));
        sldrSubOxigen.setMajorTickSpacing(20);
        sldrSubOxigen.setMinorTickSpacing(10);
        sldrSubOxigen.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrSubOxigen.setPaintLabels(true);
        sldrSubOxigen.setPaintTicks(true);
        sldrSubOxigen.setSnapToTicks(true);
        sldrSubOxigen.setValue(60);
        getContentPane().add(sldrSubOxigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, 257));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Energy");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 46, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Oxigen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 56, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Dilshani\\Defence_System\\src\\defence_system\\Submarine cover 1.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSubmarineActionPerformed

    private void btnSubSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubSendActionPerformed
           // TODO add your handling code here:
           //MainController mainController = new MainController();
           String ab = txtFieldSubmarine.getText();
           MainController.txtAreaMainIncomeMsg.append("Submarine :"+ab+"\n");
           System.out.println(txtFieldSubmarine.getText());
           txtFieldSubmarine.setText("");
    }//GEN-LAST:event_btnSubSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubSend;
    private javax.swing.JButton btnSubShoot;
    private javax.swing.JButton btnSubSonar;
    private javax.swing.JButton btnSubTomahawk;
    private javax.swing.JButton btnSubTrident;
    private javax.swing.JCheckBox chckBxSubPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubAreaClear;
    public static javax.swing.JSlider sldrSubEnergy;
    public static javax.swing.JSlider sldrSubOxigen;
    public static javax.swing.JSpinner spinerSubAmmoCount;
    public static javax.swing.JSpinner spinrSubSoldieCount;
    private javax.swing.JTextArea txtAreaSubmarine;
    private javax.swing.JTextField txtFieldSubmarine;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear(boolean clear) {
     if(clear==true){
         lblSubAreaClear.setText("Area Cleared");
     }else{
         lblSubAreaClear.setText("Area Not Cleared");
     }
    }

    @Override
    public void message(String msg, boolean checkSend, int index) {
        if(checkSend==true && index==3){
            txtAreaSubmarine.append(msg+"\n");
           //System.out.println(msg);
        } else if(checkSend == false) {
            txtAreaSubmarine.append(msg+"\n");
        }
        //jTextArea1.append(msg+"\n");
    }

    @Override
    public void strenth(int stren) {
        if(chckBxSubPosition.isSelected()){
            if(stren>0){
                btnSubShoot.setEnabled(true);
            } else {
                btnSubShoot.setEnabled(false);
            }
            if(stren>20){
                btnSubSonar.setEnabled(true);
            } else {
                btnSubSonar.setEnabled(false);
            }
            if(stren>60){
                btnSubTomahawk.setEnabled(true);
            }else{
                btnSubTomahawk.setEnabled(false);
            }
            if(stren>80){
                btnSubTrident.setEnabled(true);
            } else {
                btnSubTrident.setEnabled(false);
            }
        } else {
            btnSubShoot.setEnabled(false);
            btnSubSonar.setEnabled(false);
            btnSubTomahawk.setEnabled(false);
            btnSubTrident.setEnabled(false);
            
        }
    }
}
